rentcar:
  outputs:
    dev:
      account: LHUNCRM-BS03889
      database: RIDE_SHARE
      password: 9,e_C#v)$X:%2g5
      role: ACCOUNTADMIN
      schema: RIDE_SHARE_V1
      threads: 2
      type: snowflake
      user: ZACH27
      warehouse: COMPUTE_WH
  target: dev